# Generated by Django 2.2.24 on 2023-05-02 16:42
from django.db import migrations


NEW_BUILDING_YEAR = 2015


def mark_buildings_by_age(apps, schema_editor):
    """Mark new buildings records in database"""
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=NEW_BUILDING_YEAR).update(new_building=True)
    Flat.objects.exclude(construction_year__gte=NEW_BUILDING_YEAR).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(mark_buildings_by_age),
    ]
