# Generated by Django 3.2 on 2023-05-05 07:28

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_flat_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, default=None, null=True,
                                                                 region=None,  verbose_name='Нормализованный номер владельца'),
        ),
    ]
