# Generated by Django 2.2.24 on 2023-05-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230504_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст жалобы'),
        ),
    ]
