# Generated by Django 3.2 on 2023-05-05 15:21

import phonenumbers
from django.db import migrations


def normalize_phone_numbers(apps, schema_editor):
    """Normalize phone number to standard form"""
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all().iterator():
        flat.owner_pure_phone = None
        phone_number = flat.owners_phonenumber
        normalized_phone_number = phonenumbers.parse(phone_number, "RU")
        if phonenumbers.is_valid_number(normalized_phone_number):
            normalized_country_code = normalized_phone_number.country_code
            normalized_phone = normalized_phone_number.national_number
            flat.owner_pure_phone = f'{normalized_country_code}{normalized_phone}'
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_owner_pure_phone'),
    ]

    operations = [
         migrations.RunPython(normalize_phone_numbers),
    ]
