# Generated by Django 2.2.24 on 2023-05-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
