# Generated by Django 2.2.24 on 2023-05-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_userprofile_create_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_flats', to='property.UserProfile'),
        ),
    ]
