# Generated by Django 2.2.24 on 2023-05-05 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_who_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.UserProfile', verbose_name='Кто жаловался'),
        ),
    ]
