# Generated by Django 2.2.24 on 2023-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_flat_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_flats', to='property.UserProfile', verbose_name='кто лайкнул'),
        ),
    ]
