# Generated by Django 3.2 on 2023-05-09 14:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_flat_normalize_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='ФИО собственника')),
                ('owners_phonenumber', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='owned_by',
            field=models.ManyToManyField(blank=True, related_name='owned_flats', to='property.FlatOwner', verbose_name='владелец'),
        ),
    ]
