# Generated by Django 3.2 on 2023-05-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230509_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_name',
            field=models.CharField(max_length=100, verbose_name='ФИО владельца'),
        ),
    ]
