# Generated by Django 3.2 on 2023-05-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_link_flats_to_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
    ]
