# Generated by Django 3.2 on 2023-05-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_flats_remove_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Новостройка'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ФИО владельца'),
        ),
    ]
